### ISSUE TITLE
visualization not working

### ISSUE THREAD

**Issue by barrat** [benmaier/tacoma#13]
<img width="996" alt="untitled" src="https://user-images.githubusercontent.com/6481557/46920838-5d5ac600-cff4-11e8-94e6-9afda34d7c62.png">
Hi, I don't replicate the visualization example. I attach a screenshot of the error message.
I work on a Mac (High Sierra), python3.7 

best

**Comment by benmaier** [comment]
Apparently sometimes the javascript source code was not copied to the "~/.tacoma" subfolder prior to starting a visualization. It should work now with version 0.1.1

**Comment by benmaier** [comment]
sorry for closing this -- it happened automatically with the commit

**Comment by barrat** [comment]
actually it's still not working. However it's indeed clearly linked to the issue of not copying these javascript code. If I copy by hand the directories css, custom_js, widgets_js into .tacoma/web, then it works. However it works just once: if I stop it and try to relaunch a visualization in the same notebook, it opens a tab but does not show the animation.

**Comment by benmaier** [comment]
Thanks for the updates!

@Yacoub-Kureh closing the visualization in the browser does not send a signal back to Python so you have to send the KeyboardInterrupt-signal (Control-C in console or the "Stop" button in a Jupyter notebook) manually, as you said, so unfortunately this works as intended -- I have not found a better solution to this problem yet. The 404 messages correspond to two images not being found. Is the visualization running otherwise?

@barrat I can reproduce the error that a visualization can't be restarted once another has been started in the same session. I'm going to open another issue with this problem and look into it asap.

Meanwhile, I'll be working to fix the issue of copying the visualization files.

**Comment by benmaier** [comment]
I found the bug concerning the JS-files -- some subdirectories were not included in the `MANIFEST.in` which I did not recognize because I falsely kept working with the development install. Those files were then not copied.

It should now really work with version `0.1.4`.

**Comment by benmaier** [comment]
Visualizations  now work multiple times per session (fixed #14)

**Comment by barrat** [comment]
Works indeed for me now. Thanks a lot!

**Comment by benmaier** [comment]
Great! Thanks for raising this issue!
